import Head from "next/head";
import Image from "next/image";
import SelectTag from "../components/SelectTag/SelectTag";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<nav className={styles.nav}>
				<h1 className={styles.navHeading}>gravvity</h1>
			</nav>
			<main className={styles.main}>
				<div className={styles.content}>
					<div className={styles.image}></div>
					<div className={styles.formContainer}>
						<div className={styles.form}>
							<div className={styles.formHeadingsContainer}>
								<h1>Live Crypto Updates</h1>
								<p>
									Get <span>realtime</span> crypto-coin updates in just{" "}
									<span>1 email</span>
								</p>
							</div>
							<div className={styles.formInputContainer}>
								<div>
									<label htmlFor="email">Email</label>
									<input type="email" id="email" placeholder="Email" />
								</div>
								<div>
									<label htmlFor="email">Email</label>
									<SelectTag />
								</div>
							</div>
							<button>subscribe</button>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
